# Generated by Django 2.2b1 on 2019-03-17 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autonomy', models.TextField(blank=True, max_length=500)),
                ('relatedness', models.TextField(blank=True, max_length=500)),
                ('competence', models.TextField(blank=True, max_length=500)),
                ('autonomy_2', models.TextField(blank=True, max_length=500)),
                ('relatedness_2', models.TextField(blank=True, max_length=500)),
                ('competence_2', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
