# Generated by Django 2.2b1 on 2019-03-17 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Gaziantep', 'Gaziantep, Turkey'), ('London', 'London, United Kingdom'), ('Madrid', 'Madrid, Spain'), ('Stockholm', 'Stockholm, Sweden')], default='Stockholm', max_length=24)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('LGBT-Q', 'LGBT-Q'), ('Rather Not Say', 'Rather Not Say')], default='Rather Not Say', max_length=24)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=24)),
                ('is_educator', models.BooleanField(default=True)),
                ('is_mentor', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
